const fs = require('fs');
let code = fs.readFileSync('e:/cod2/KSK_Lai_Xe_TT36 290626.html', 'utf8');

const oldRenderEdit = "function renderEdit(){let p=patients[current]||newPatient();let html='<div class=\"grid2\">';FIELDS.forEach(([id,label])=>{let isLong=['hoKhau','tienSuGiaDinh','benhSuBanThan','dangDieuTri','ketLuan','tamThan','thanKinh','matBenh','tmh','timMach','hoHap','coXuongKhop','noiTiet','maTuyKQ','xetNghiemKhacKQ'].includes(id);html+=`<div class=\"editField\" style=\"${isLong?'grid-column:1/-1':''}\"><label>${esc(label)}</label>${isLong?`<textarea oninput=\"patients[current]['${id}']=this.value;saveData();renderPreview()\">${esc(p[id])}</textarea>`:(id==='gioiTinh'?`<input list=\"genderOptions\" value=\"${esc(p.gioiTinh||'')}\" placeholder=\"Nhập hoặc chọn Nam / Nữ / Khác\" oninput=\"patients[current]['gioiTinh']=formatGender(this.value);saveData();renderList();renderPreview()\"><datalist id=\"genderOptions\"><option value=\"Nam\"></option><option value=\"Nữ\"></option><option value=\"Khác\"></option></datalist>`:`<input value=\"${esc(p[id])}\" oninput=\"patients[current]['${id}']=this.value;if('${id}'==='ngaySinh'||'${id}'==='ngayKetLuan'||'${id}'==='ngayKham'){let a=calcAgeFromBirth(patients[current].ngaySinh,patients[current].ngayKetLuan||patients[current].ngayKham);if(a)patients[current].tuoi=a;}saveData();renderList();renderEdit();renderPreview()\">`)}</div>`});html+='</div><div class=\"hint\"><b>Tiền sử bệnh:</b> chọn Có/Không cho từng mục bên dưới.</div><div class=\"grid1\">';BOOLS.forEach(b=>{html+=`<div class=\"editField\"><label>${esc(b)}</label><select onchange=\"patients[current].bool=patients[current].bool||{};patients[current].bool['${esc(b)}']=this.value;saveData();renderPreview()\"><option ${p.bool?.[b]!=='Có'?'selected':''}>Không</option><option ${p.bool?.[b]==='Có'?'selected':''}>Có</option></select></div>`});html+='</div><div class=\"hint\">Ảnh 4x6: bấm vào khung ảnh trên mẫu xem trước để chọn ảnh cho hồ sơ đang chọn.</div>';document.getElementById('editBox').innerHTML=html}";

const newRenderEdit = "function renderEdit(){let actId=document.activeElement?.id;let actStart=document.activeElement?.selectionStart;let actEnd=document.activeElement?.selectionEnd;let p=patients[current]||newPatient();let html='<div class=\"grid2\">';FIELDS.forEach(([id,label])=>{let isLong=['hoKhau','tienSuGiaDinh','benhSuBanThan','dangDieuTri','ketLuan','tamThan','thanKinh','matBenh','tmh','timMach','hoHap','coXuongKhop','noiTiet','maTuyKQ','xetNghiemKhacKQ'].includes(id);html+=`<div class=\"editField\" style=\"${isLong?'grid-column:1/-1':''}\"><label>${esc(label)}</label>${isLong?`<textarea id=\"inp_${id}\" oninput=\"patients[current]['${id}']=this.value;saveData();renderPreview()\">${esc(p[id])}</textarea>`:(id==='gioiTinh'?`<input id=\"inp_${id}\" list=\"genderOptions\" value=\"${esc(p.gioiTinh||'')}\" placeholder=\"Nhập hoặc chọn Nam / Nữ / Khác\" oninput=\"patients[current]['gioiTinh']=formatGender(this.value);saveData();renderList();renderPreview()\"><datalist id=\"genderOptions\"><option value=\"Nam\"></option><option value=\"Nữ\"></option><option value=\"Khác\"></option></datalist>`:`<input id=\"inp_${id}\" value=\"${esc(p[id])}\" oninput=\"patients[current]['${id}']=this.value;if('${id}'==='ngaySinh'||'${id}'==='ngayKetLuan'||'${id}'==='ngayKham'){let a=calcAgeFromBirth(patients[current].ngaySinh,patients[current].ngayKetLuan||patients[current].ngayKham);if(a)patients[current].tuoi=a;}saveData();renderList();renderEdit();renderPreview()\">`)}</div>`});html+='</div><div class=\"hint\"><b>Tiền sử bệnh:</b> chọn Có/Không cho từng mục bên dưới.</div><div class=\"grid1\">';BOOLS.forEach(b=>{html+=`<div class=\"editField\"><label>${esc(b)}</label><select id=\"sel_${esc(b)}\" onchange=\"patients[current].bool=patients[current].bool||{};patients[current].bool['${esc(b)}']=this.value;saveData();renderPreview()\"><option ${p.bool?.[b]!=='Có'?'selected':''}>Không</option><option ${p.bool?.[b]==='Có'?'selected':''}>Có</option></select></div>`});html+='</div><div class=\"hint\">Ảnh 4x6: bấm vào khung ảnh trên mẫu xem trước để chọn ảnh cho hồ sơ đang chọn.</div>';document.getElementById('editBox').innerHTML=html;if(actId){let el=document.getElementById(actId);if(el){el.focus();try{el.setSelectionRange(actStart,actEnd)}catch(e){}}}}";

if(code.includes(oldRenderEdit)){
  code = code.replace(oldRenderEdit, newRenderEdit);
  fs.writeFileSync('e:/cod2/KSK_Lai_Xe_TT36 290626.html', code, 'utf8');
  console.log('Fixed focus issue');
} else {
  console.log('Could not find oldRenderEdit exactly.');
}
